version: "3.9"
services:
  db:
    container_name: postgres_prisma
    image: postgres:15.3
    build:
      context: ./
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      PGDATA: /data/sample
    ports:
      - "5433:5432"
  pgadmin4:
    container_name: pgadmin4_prisma
    image: dpage/pgadmin4
    ports:
      - 8889:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sample@gmail.com
      PGADMIN_DEFAULT_PASSWORD: sample_password
    hostname: pgadmin4
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin4_data:
